version: "3.8"
services:
  pgdb:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postGres:/var/lib/postgresql/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  projectName:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn start"
    volumes:
      - .:/DirectoryName
